ALTER TABLE meals
  DROP CONSTRAINT FK677c66qpjr7234luomahc1ale;

ALTER TABLE user_roles
  DROP CONSTRAINT FKhfh9dx7w3ubf1co1vdev94g3f;

DROP TABLE IF EXISTS meals CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP SEQUENCE IF EXISTS global_seq;
